### ISSUE TITLE
Add widely-used operators

### ISSUE THREAD

**Issue by cN3rd** [Irrational-Encoding-Wizardry/vsutil#10]
Add some basic image processing operators to vsutil, e.g.:

- Simple (convolution-based) edge masks/gradients: [kirsch](https://github.com/Irrational-Encoding-Wizardry/kagefunc/blob/master/kagefunc.py#L255), [fast sobel](https://github.com/Irrational-Encoding-Wizardry/kagefunc/blob/master/kagefunc.py#L266).
- Simple blurring kernels (gaussian, uniform), and perhaps low-pass/high-pass functions.
- Image morphology operators which aren't implemented in the core (see https://github.com/IFeelBloated/Vine/blob/master/Vine.py#L65)

Implementing these in the scope of vsutil would save the hassle of re-implementing these on every `xxxfuncs` and serve an example of best coding practices within VapourSynth.

(Pardon my english.)

**Comment by kageru** [comment]
The fast sobel serves no purpose anymore as the limits that made std.Sobel slower have been removed. I should delete it from kagefunc.
Kirsch isn’t that much more useful. Sobel is enough for use cases that require a simple edge mask.

If I see the blur and low/high-pass in enough other functions, I’ll consider them. I just don’t know too many scripts that use them, but I’ll look into that.

The morphology filters sound like a good addition, but I don’t want to copy someone’s code without asking. I should probably look into these myself and implement what I consider useful, unless IFeelBloated wants to submit a PR here.
