### ISSUE TITLE
djcj seems to be gone.

### ISSUE THREAD

**Issue by stuxcrystal** [Irrational-Encoding-Wizardry/vsutil#23]
It is requirement for the circle-ci-image though.

https://github.com/vapoursynth/vapoursynth/issues/443

**Comment by Baa14453** [comment]
![1208 - 7I8scTI](https://user-images.githubusercontent.com/9057997/56923037-77a44f00-6ac1-11e9-8b2d-513ebface846.png)

**Comment by theChaosCoder** [comment]
Come to the Dark side of the Force https://github.com/YaLTeR/vapoursynth-rs/blob/master/appveyor.yml#L62-L63

**Comment by stuxcrystal** [comment]
Nah. I'll keep using PIP.

@theChaosCoder 

P.S. Shameless plug: https://warehouse.encode.moe

**Comment by theChaosCoder** [comment]
You have a type in FAQ -> "IS" not it kinda shit* :P

**Comment by stuxcrystal** [comment]
@theChaosCoder ok. I fixed the faq.
