### ISSUE TITLE
Make "real" release for vsrepo

### ISSUE THREAD

**Issue by theChaosCoder** [Irrational-Encoding-Wizardry/vsutil#24]
Is it possible to make a real release instead of just tagging it? Because of that releases are in fact empty and that means no auto update via vsrepo.
- https://api.github.com/repos/Irrational-Encoding-Wizardry/vsutil/releases
- https://api.github.com/repos/Irrational-Encoding-Wizardry/vsutil/tags

p.s. And maybe make a thread on doom9 for vsutil? :-)

**Comment by stuxcrystal** [comment]
Can we not use the zipball for the release? zipball_url would suffice.

**Comment by stuxcrystal** [comment]
Never mind. Fixed.
