### ISSUE TITLE
Bump setup.py version number

### ISSUE THREAD

**Issue by heicrd** [Irrational-Encoding-Wizardry/vsutil#40]
The version specified in setup.py is still `0.0.1`, which conflicts with `0.0.3` being tagged on github and `0.0.2` being released on pypi. This means that pip does not correctly recognize manually-installed versions of vsutil, which is necessary for a number of reverse-dependencies due to `depth` not being included in any version currently available on pypi.

**Comment by stuxcrystal** [comment]
I bumped the setup.py version and uploaded the new version to PyPI.
