### ISSUE TITLE
vsutil in vsrepo is outdated

### ISSUE THREAD

**Issue by iamtherobin** [Irrational-Encoding-Wizardry/vsutil#67]
Not sure who is responsible for the vsrepo update, but posting here anyways.

vsrepo offers version 0.5 of vsutil which is very outdated. Even the release version 0.6 is outdated now. The latest git is needed for huvsfunc to import newest functions. Without vsrepo getting updated, havsfunc.py is breaking now.

**Comment by LightArrowsEXE** [comment]
This issue has been brought up half a year ago [here](https://github.com/vapoursynth/vsrepo/issues/168), and it's no closer to being resolved than it was back then. :/

**Comment by RivenSkaye** [comment]
This has since been fixed, can anyone close this issue? All sources (vsrepo, GH releases and PyPI) list 0.8.0 as the latest release
