### ISSUE TITLE
Release 0.8.0

### ISSUE THREAD

**Issue by nobananasforyou** [Irrational-Encoding-Wizardry/vsutil#75]
The latest release doesn't show on the 'Releases' tab but rather shows on the 'Tags' tab.
![Screenshot 2022-08-03 at 02-00-44 Release 0 8 0 · Issue #75 · Irrational-Encoding-Wizardry_vsutil](https://user-images.githubusercontent.com/50061008/182472628-96c189dc-cabd-4702-8404-10bb4f0fc05a.png)

**Comment by kageru** [comment]
Created a release for the tag.
