### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by kageru** [Irrational-Encoding-Wizardry/vsutil#8]
Despite how young this project is, we already had a few bad or broken commits.
We should implement tests to ensure this doesn’t happen. Ideally, every method should have at least one test, if not multiple for multiple branches.

I’ve written a few simple test helpers for kagefunc which might be useful here as well. Do we want to add a testing util to this repo or should that be a separate project?
Methods in question: https://github.com/Irrational-Encoding-Wizardry/kagefunc/blob/master/tests.py#L85

**Comment by stuxcrystal** [comment]
Yuuno uses Circle-CI for it's automated testing. You can use this configuration for implement automated CI based testing.

https://github.com/Irrational-Encoding-Wizardry/yuuno-core/blob/master/.circleci/config.yml

**Comment by kageru** [comment]
@stuxcrystal sounds good. Any opinions on the testing utils?

**Comment by stuxcrystal** [comment]
They sound interesting.

**Comment by kageru** [comment]
We reached 100%, so this is closed now. Reducing the coverage will not be allowed for future commits.
