### ISSUE TITLE
Create a setup.py for the project

### ISSUE THREAD

**Issue by stuxcrystal** [Irrational-Encoding-Wizardry/vsutil#9]
This would help me including vsutil to Yuuno.

**Comment by kageru** [comment]
Could you make a PR for that? I think you know more about Python packaging than anyone else here.

**Comment by stuxcrystal** [comment]
I will get to it.

 

Von: kageru <notifications@github.com> 
Gesendet: Donnerstag, 7. März 2019 09:45
An: Irrational-Encoding-Wizardry/vsutil <vsutil@noreply.github.com>
Cc: Roland Netzsch <stuxcrystal@encode.moe>; Author <author@noreply.github.com>
Betreff: Re: [Irrational-Encoding-Wizardry/vsutil] Create a setup.py for the project (#9)

 

Could you make a PR for that? I think you know more about Python packaging than anyone else here.

**Comment by stuxcrystal** [comment]
I got to it.
